/* The following code was generated by JFlex 1.6.1 */


import java.io.*;
import java_cup.runtime.*;

class Symbol {

	public String content;
	public TokenType tokenType;
	public int yyline, yycolumn;

	public Symbol( TokenType tokenType, int yyline, int yycolumn, String content ) {
		this.content = content;
		this.tokenType = tokenType;
		this.yyline = yyline;
		this.yycolumn = yycolumn;
	}

}

enum TokenType {

	AUTO, DOUBLE,
	INT, STRUCT,
	CONST, FLOAT,
	SHORT, UNSIGNED,
	BREAK, ELSE,
	LONG, SWITCH,
	CONTINUE, FOR,
	SIGNED, VOID,
	CASE, ENUM,
	REGISTER, TYPEDEF,
	DEFAULT, GOTO,
	SIZEOF, VOLATILE,
	CHAR, EXTERN,
	RETURN, UNION,
	DO, IF,
	STATIC, WHILE;

}


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>Scanner.flex</tt>
 */
public class MyScanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\141\0\1\1\1\6\1\15\1\5\1\10\1\16\1\20\1\17\1\11"+
    "\1\0\1\21\1\7\1\24\1\12\1\4\1\26\1\0\1\14\1\13"+
    "\1\3\1\2\1\23\1\22\1\30\1\25\1\27\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff95\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\23\0\1\1\7\0\1\2\30\0\1\3\13\0\1\4"+
    "\5\0\1\5\6\0\1\6\1\7\1\10\11\0\1\11"+
    "\2\0\1\12\1\0\1\13\2\0\1\14\1\15\4\0"+
    "\1\16\5\0\1\17\4\0\1\20\1\21\1\22\3\0"+
    "\1\23\1\0\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\4\0\1\33\1\34\3\0\1\35\1\36\1\37"+
    "\1\40";

  private static int [] zzUnpackAction() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\31\0\62\0\113\0\144\0\175\0\226\0\257"+
    "\0\310\0\341\0\372\0\u0113\0\u012c\0\u0145\0\u015e\0\u0177"+
    "\0\u0190\0\u01a9\0\u01c2\0\u01db\0\u01f4\0\u020d\0\u0226\0\u023f"+
    "\0\u0258\0\u0271\0\u028a\0\u02a3\0\u02bc\0\u02d5\0\u02ee\0\u0307"+
    "\0\u0320\0\u0339\0\u0352\0\u036b\0\u0384\0\u039d\0\u03b6\0\u03cf"+
    "\0\u03e8\0\u0401\0\u041a\0\u0433\0\u044c\0\u0465\0\u047e\0\u0497"+
    "\0\u04b0\0\u04c9\0\u04e2\0\u04fb\0\u02a3\0\u0514\0\u052d\0\u0546"+
    "\0\u055f\0\u0578\0\u0591\0\u05aa\0\u05c3\0\u05dc\0\u05f5\0\u060e"+
    "\0\u02a3\0\u0627\0\u0640\0\u0659\0\u0672\0\u068b\0\u02a3\0\u06a4"+
    "\0\u06bd\0\u06d6\0\u06ef\0\u0708\0\u0721\0\u02a3\0\u02a3\0\u02a3"+
    "\0\u073a\0\u0753\0\u076c\0\u0785\0\u079e\0\u07b7\0\u07d0\0\u07e9"+
    "\0\u0802\0\u02a3\0\u081b\0\u0834\0\u02a3\0\u084d\0\u02a3\0\u0866"+
    "\0\u087f\0\u02a3\0\u02a3\0\u0898\0\u08b1\0\u08ca\0\u08e3\0\u02a3"+
    "\0\u08fc\0\u0915\0\u092e\0\u0947\0\u0960\0\u02a3\0\u0979\0\u0992"+
    "\0\u09ab\0\u09c4\0\u02a3\0\u02a3\0\u02a3\0\u09dd\0\u09f6\0\u0a0f"+
    "\0\u02a3\0\u0a28\0\u02a3\0\u02a3\0\u02a3\0\u02a3\0\u02a3\0\u02a3"+
    "\0\u02a3\0\u0a41\0\u0a5a\0\u0a73\0\u0a8c\0\u02a3\0\u02a3\0\u0aa5"+
    "\0\u0abe\0\u0ad7\0\u02a3\0\u02a3\0\u02a3\0\u02a3";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\0\1\5\1\6\1\7"+
    "\1\10\1\11\1\0\1\12\1\13\1\14\1\15\1\0"+
    "\1\16\1\0\1\17\1\20\7\0\1\21\40\0\1\22"+
    "\43\0\1\23\7\0\1\24\3\0\1\25\34\0\1\26"+
    "\20\0\1\27\33\0\1\30\2\0\1\31\15\0\1\32"+
    "\12\0\1\33\3\0\1\34\15\0\1\35\5\0\1\36"+
    "\5\0\1\37\2\0\1\40\16\0\1\41\21\0\1\42"+
    "\2\0\1\43\12\0\1\44\15\0\1\45\2\0\1\46"+
    "\25\0\1\47\43\0\1\50\15\0\1\51\27\0\1\52"+
    "\36\0\1\53\1\0\1\54\43\0\1\55\4\0\1\56"+
    "\44\0\1\57\22\0\1\60\32\0\1\61\31\0\1\62"+
    "\17\0\1\63\31\0\1\64\30\0\1\65\57\0\1\66"+
    "\12\0\1\67\34\0\1\70\6\0\1\71\5\0\1\72"+
    "\35\0\1\73\22\0\1\74\14\0\1\75\23\0\1\76"+
    "\27\0\1\77\17\0\1\100\43\0\1\101\20\0\1\102"+
    "\27\0\1\103\36\0\1\104\26\0\1\105\1\0\1\106"+
    "\23\0\1\107\30\0\1\110\35\0\1\111\27\0\1\112"+
    "\26\0\1\113\23\0\1\114\30\0\1\115\47\0\1\116"+
    "\20\0\1\117\44\0\1\120\14\0\1\121\23\0\1\122"+
    "\27\0\1\123\40\0\1\124\26\0\1\125\34\0\1\126"+
    "\17\0\1\127\27\0\1\130\37\0\1\131\27\0\1\132"+
    "\23\0\1\133\7\0\1\134\31\0\1\135\15\0\1\136"+
    "\33\0\1\137\33\0\1\140\22\0\1\141\34\0\1\142"+
    "\35\0\1\143\36\0\1\144\15\0\1\145\32\0\1\146"+
    "\23\0\1\147\47\0\1\150\23\0\1\151\25\0\1\152"+
    "\34\0\1\153\23\0\1\154\24\0\1\155\27\0\1\156"+
    "\42\0\1\157\27\0\1\160\27\0\1\161\26\0\1\162"+
    "\22\0\1\163\30\0\1\164\35\0\1\165\23\0\1\166"+
    "\37\0\1\167\26\0\1\170\30\0\1\171\27\0\1\172"+
    "\33\0\1\173\33\0\1\174\16\0\1\175\32\0\1\176"+
    "\41\0\1\177\31\0\1\200\23\0\1\201\21\0\1\202"+
    "\37\0\1\203\27\0\1\204\27\0\1\205\36\0\1\206"+
    "\15\0\1\207\35\0\1\210\22\0\1\211\35\0\1\212"+
    "\26\0\1\213\37\0\1\214\24\0\1\215\30\0\1\216"+
    "\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2800];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\23\0\1\1\7\0\1\11\30\0\1\11\13\0\1\11"+
    "\5\0\1\11\6\0\3\11\11\0\1\11\2\0\1\11"+
    "\1\0\1\11\2\0\2\11\4\0\1\11\5\0\1\11"+
    "\4\0\3\11\3\0\1\11\1\0\7\11\4\0\2\11"+
    "\3\0\4\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[142];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public MyScanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 88) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol readNext() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return null;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol( TokenType.DO, yyline, yycolumn, "do" );
            }
          case 33: break;
          case 2: 
            { return new Symbol( TokenType.IF, yyline, yycolumn, "if" );
            }
          case 34: break;
          case 3: 
            { return new Symbol( TokenType.INT, yyline, yycolumn, "int" );
            }
          case 35: break;
          case 4: 
            { return new Symbol( TokenType.FOR, yyline, yycolumn, "for" );
            }
          case 36: break;
          case 5: 
            { return new Symbol( TokenType.AUTO, yyline, yycolumn, "auto" );
            }
          case 37: break;
          case 6: 
            { return new Symbol( TokenType.LONG, yyline, yycolumn, "long" );
            }
          case 38: break;
          case 7: 
            { return new Symbol( TokenType.ELSE, yyline, yycolumn, "else" );
            }
          case 39: break;
          case 8: 
            { return new Symbol( TokenType.ENUM, yyline, yycolumn, "enum" );
            }
          case 40: break;
          case 9: 
            { return new Symbol( TokenType.CASE, yyline, yycolumn, "case" );
            }
          case 41: break;
          case 10: 
            { return new Symbol( TokenType.CHAR, yyline, yycolumn, "char" );
            }
          case 42: break;
          case 11: 
            { return new Symbol( TokenType.GOTO, yyline, yycolumn, "goto" );
            }
          case 43: break;
          case 12: 
            { return new Symbol( TokenType.VOID, yyline, yycolumn, "void" );
            }
          case 44: break;
          case 13: 
            { return new Symbol( TokenType.UNION, yyline, yycolumn, "union" );
            }
          case 45: break;
          case 14: 
            { return new Symbol( TokenType.BREAK, yyline, yycolumn, "break" );
            }
          case 46: break;
          case 15: 
            { return new Symbol( TokenType.SHORT, yyline, yycolumn, "short" );
            }
          case 47: break;
          case 16: 
            { return new Symbol( TokenType.CONST, yyline, yycolumn, "const" );
            }
          case 48: break;
          case 17: 
            { return new Symbol( TokenType.FLOAT, yyline, yycolumn, "float" );
            }
          case 49: break;
          case 18: 
            { return new Symbol( TokenType.WHILE, yyline, yycolumn, "while" );
            }
          case 50: break;
          case 19: 
            { return new Symbol( TokenType.DOUBLE, yyline, yycolumn, "double" );
            }
          case 51: break;
          case 20: 
            { return new Symbol( TokenType.EXTERN, yyline, yycolumn, "extern" );
            }
          case 52: break;
          case 21: 
            { return new Symbol( TokenType.STATIC, yyline, yycolumn, "static" );
            }
          case 53: break;
          case 22: 
            { return new Symbol( TokenType.STRUCT, yyline, yycolumn, "struct" );
            }
          case 54: break;
          case 23: 
            { return new Symbol( TokenType.SIGNED, yyline, yycolumn, "signed" );
            }
          case 55: break;
          case 24: 
            { return new Symbol( TokenType.SIZEOF, yyline, yycolumn, "sizeof" );
            }
          case 56: break;
          case 25: 
            { return new Symbol( TokenType.SWITCH, yyline, yycolumn, "switch" );
            }
          case 57: break;
          case 26: 
            { return new Symbol( TokenType.RETURN, yyline, yycolumn, "return" );
            }
          case 58: break;
          case 27: 
            { return new Symbol( TokenType.TYPEDEF, yyline, yycolumn, "typedef" );
            }
          case 59: break;
          case 28: 
            { return new Symbol( TokenType.DEFAULT, yyline, yycolumn, "default" );
            }
          case 60: break;
          case 29: 
            { return new Symbol( TokenType.UNSIGNED, yyline, yycolumn, "unsigned" );
            }
          case 61: break;
          case 30: 
            { return new Symbol( TokenType.REGISTER, yyline, yycolumn, "register" );
            }
          case 62: break;
          case 31: 
            { return new Symbol( TokenType.CONTINUE, yyline, yycolumn, "continue" );
            }
          case 63: break;
          case 32: 
            { return new Symbol( TokenType.VOLATILE, yyline, yycolumn, "volatile" );
            }
          case 64: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
